### ISSUE TITLE
Duplicated/Incorrect PRs listed

### ISSUE THREAD

**Issue by whyman** [release-drafter/release-drafter#221] opened 2019-05-27 09:56 UTC
Hi,

I am getting some random very old PRs linked, or incorrect IDs or something strange.

As you can see below "Fixture Upgrade" is duplicated and the 2nd one links to a random old PR. 

Project is OSS: here is the config: https://github.com/gerbera/gerbera/blob/master/.github/release-drafter.yml

Please help!

---
![image](https://user-images.githubusercontent.com/345034/58412165-c8ca4300-806d-11e9-96d5-16e42485530c.png)

**Comment by casz** [comment] 2019-05-27 16:24
@TimonVS I believe the GraphQL is doing something unexpected

**Comment by TimonVS** [comment] 2019-05-27 18:40
I think I see what's going on here, the duplicate PRs are coming from forks. I will create a PR to filter those out :)
Thanks for reporting!

**Comment by TimonVS** [comment] 2019-06-24 17:15
I'm reopening this issue because the fix I created turned out to be wrong. I will work on a definitive fix.

**Comment by v00d00** [comment] 2019-07-01 07:16
Any news?

**Comment by TimonVS** [comment] 2019-07-01 18:52
Hey @v00d00, I've thought out the following solution:

We change the query in [`lib/commits.js`](https://github.com/toolmantim/release-drafter/blob/master/lib/commits.js#L5) to the following:

```diff
...
                associatedPullRequests(first: 5) {
                  nodes {
+                   baseRepository {
+                     nameWithOwner
+                   }
                    url
                    title
                    number
                    author {
                      login
                    }
                    mergedAt
                    isCrossRepository
                    labels(first: 10) {
                      nodes {
                        name
                      }
                    }
...
```

Then we filter out all PRs where `baseRepository.nameWithOwner` is not equal to the name with owner of the repository we're generating the changelog for.

I think this should be the solution but I haven't tested it yet and there might still be some edge cases that I haven't thought of. I'm was also wondering if we should create an option for people to include PRs from forks in the changelog? Probably not though.

I've created a draft PR with the changes: https://github.com/toolmantim/release-drafter/pull/251. Though it doesn't include tests yet. If you're using the Actions version of Release Drafter you should be able to test it by changing the `.github/main.workflow` file:

```diff
workflow "Push" {
  on = "push"
  resolves = ["Draft Release"]
}

action "Draft Release" {
- uses = "toolmantim/release-drafter@v5.2.0"
+ uses = "TimonVS/release-drafter@fix/221"
  secrets = ["GITHUB_TOKEN"]
}
```

**Comment by v00d00** [comment] 2019-07-08 13:10
Unfortunately we use the "app" version.

**Comment by rnorth** [comment] 2019-10-26 08:02
We've just noticed this problem over in testcontainers/testcontainers-java, with a PR from our repo into someone's fork ending up in our draft release notes. [This is the PR that caused it](https://github.com/eltabo/testcontainers-java/pull/1), triggering an entry in our release draft like this:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/132175/67616304-2b676c80-f7cf-11e9-9f40-5e88038eb49c.png">


Strangely I've been unable to reproduce it myself today, though.

@toolmantim is it possible that this has been fixed in the last couple of weeks?

**Comment by toolmantim** [comment] 2019-10-29 06:20
Strange! I haven't released an update in quite a while @rnorth…

**Comment by casz** [comment] 2019-10-29 06:29
@toolmantim Just from a logic the draft PR @TimonVS seems to solve the problem #251

**Comment by jetersen** [comment] 2020-05-26 20:10
I'd like resume work adding a test.

**Closed** 2020-05-26 23:33 UTC

**Comment by jetersen** [comment] 2020-05-26 23:46
@rnorth Thanks for pointing to a PR, made it easier to recreate a test.

I'll see if I can land a release to the app tomorrow or at least this week 😅
Few more PRs that would be nice to land.
